"""Reads in one of the data files generated by `generate_input.py`
   Uses the json version to make life easier.
"""

import json

with open("./data/small.json") as f:
    data = json.load(f)


for process in data["jobs"]:
    print(process)
