"""Reads in one of the data files generated by `generate_input.py`
   Pulls each part out of the row. This is if you don't like the json format
"""

with open("./data/small.dat") as f:
    data = f.read().split("\n")


for process in data:
    if len(process) > 0:
        parts = process.split(" ")
        arrival = parts[0]
        pid = parts[1]
        priority = parts[2]
        cpuBursts = parts[3::2]
        ioBursts = parts[4::2]

        print(f"{arrival}, {pid}, {priority} {cpuBursts} {ioBursts}")
